import { apiClient } from './apiClient';

export const getAdminDashboard = () => apiClient('/admin/dashboard');
export const getAdminDashboardBranches = () => apiClient('/admin/dashboard/branches');
export const getAdminDashboardUsers = () => apiClient('/admin/dashboard/users');
export const getAdminDashboardSales = () => apiClient('/admin/dashboard/sales');
export const getAdminDashboardBranchesList = () => apiClient('/admin/dashboard/branches-list');
export const getAllManagers = () => apiClient('/admin/managers');
export const getPendingManagers = () => apiClient('/admin/managers/pending');
export const getActivatedManagers = () => apiClient('/admin/managers/activated');
export const getManagersByBranch = (branchId) => apiClient(`/admin/managers/branch/${branchId}`);
export const activateManager = (userId) => apiClient(`/admin/managers/${userId}/activate`, { method: 'PUT' });
export const deactivateManager = (userId) => apiClient(`/admin/managers/${userId}/deactivate`, { method: 'PUT' });
export const getManagerDashboard = () => apiClient('/manager/dashboard');
export const getManagerBranchOverview = () => apiClient('/manager/dashboard/branch');
export const getManagerInventorySummary = () => apiClient('/manager/dashboard/inventory');
export const getManagerSalesSummary = () => apiClient('/manager/dashboard/sales');
export const getManagerNotifications = () => apiClient('/manager/dashboard/notifications');
export const createStaff = (data) => apiClient('/manager/staff', { method: 'POST', body: JSON.stringify(data) });
export const getAllStaff = () => apiClient('/manager/staff');
export const updateStaff = (userId, data) => apiClient(`/manager/staff/${userId}`, { method: 'PUT', body: JSON.stringify(data) });
export const removeStaff = (userId) => apiClient(`/manager/staff/${userId}`, { method: 'DELETE' });
export const resetStaffPassword = (userId) => apiClient(`/manager/staff/${userId}/reset-password`, { method: 'POST' });
export const getAllMedicines = () => apiClient('/manager/medicines');
export const getMedicineDetails = (medicineId) => apiClient(`/manager/medicines/${medicineId}`);
export const addMedicine = (data) => apiClient('/manager/medicines', { method: 'POST', body: JSON.stringify(data) });
export const updateMedicineStock = (medicineId, data) => apiClient(`/manager/medicines/${medicineId}/stock`, { method: 'PUT', body: JSON.stringify(data) });
export const removeMedicine = (medicineId) => apiClient(`/manager/medicines/${medicineId}`, { method: 'DELETE' });
export const getPharmacistMedicines = () => apiClient('/pharmacist/medicines');
export const searchMedicines = (params) => apiClient(`/pharmacist/medicines/search?${new URLSearchParams(params).toString()}`);
export const getMedicinesByCategory = (categoryId) => apiClient(`/pharmacist/medicines/category/${categoryId}`);
export const getPharmacistMedicineDetails = (medicineId) => apiClient(`/pharmacist/medicines/${medicineId}`);
export const pharmacistAddMedicine = (data) => apiClient('/pharmacist/medicines', { method: 'POST', body: JSON.stringify(data) });
export const pharmacistUpdateMedicineStock = (medicineId, data) => apiClient(`/pharmacist/medicines/${medicineId}/stock`, { method: 'PUT', body: JSON.stringify(data) });
export const pharmacistRemoveMedicine = (medicineId) => apiClient(`/pharmacist/medicines/${medicineId}`, { method: 'DELETE' });
export const requestRestock = (data) => apiClient('/pharmacist/inventory/request-restock', { method: 'POST', body: JSON.stringify(data) });
export const markLowStock = (data) => apiClient('/pharmacist/inventory/mark-low-stock', { method: 'POST', body: JSON.stringify(data) });
export const getStockHistory = () => apiClient('/pharmacist/inventory/stock-history');
